spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DATABASE_URL}:jdbc:postgresql://localhost:5432/postgres"
    username: "${DATABASE_USERNAME}:postgres"
    password: "${DATABASE_PASSWORD}:postgres"
  jpa:
    hibernate:
      ddl-auto: update