spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}"
    username: "${DATABASE_USER:postgres}"
    password: "${DATABASE_PASSWORD:postgres}"
  jpa:
    hibernate:
      ddl-auto: create

amazon:
  s3:
    upload-bucket-name: "${AMAZON_S3_BUCKET:UPLOAD_BUCKET}"
    endpoint: "${AMAZON_S3_ENDPOINT:http://localhost:9090}"
    access-key: "${AMAZON_S3_ACCESS_KEY:admin}"
    secret-key: "${AMAZON_S3_SECRET_KEY:password}"

logging:
  level:
    org:
      springframework:
        security: debug